<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
            schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cellforge_viewer</name>
  <version>0.1.1</version>
  <description>CellForge Qt6/OCCT 3D viewer library</description>
  <maintainer email="contact@cellforge.dev">CellForge</maintainer>
  <license>MIT</license>

  <buildtool_depend>ros_industrial_cmake_boilerplate</buildtool_depend>

  <depend>qt6-widgets</depend>
  <depend>opencascade</depend>
</package>
